#!/usr/bin/env bash
set -euo pipefail
RUN_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$RUN_DIR/RUNINFO.txt"
RAW="$RUN_DIR/netlist_template/raw"
rm -rf "$RAW"; mkdir -p "$RAW"
# Prefer the newest input.scs generated by the template OCEAN run.
SRC_INPUT="$(find /home/s5117909/simulation "$RUN_DIR" -name input.scs -type f 2>/dev/null | sort -r | head -1 || true)"
if [ -z "$SRC_INPUT" ]; then echo "ERROR: could not find generated input.scs" >&2; exit 1; fi
cp -a "$(dirname "$SRC_INPUT")"/. "$RAW"/
[ -f "$RUN_DIR/support/ade_e.scs" ] && cp -f "$RUN_DIR/support/ade_e.scs" "$RAW/ade_e.scs"
# Patch one template case path to placeholders. These are deliberately broad.
ST1_TEMPLATE_PATH="$(find "$SPIKE_DIR/st_1" -name 'trial_*.pwl' | sort | head -1)"
ST2_TEMPLATE_PATH="$(find "$SPIKE_DIR/st_2" -name 'trial_*.pwl' | sort | head -1)"
python3 - "$RAW" "$ST1_TEMPLATE_PATH" "$ST2_TEMPLATE_PATH" <<'PY'
import pathlib, sys
root=pathlib.Path(sys.argv[1]); st1=sys.argv[2]; st2=sys.argv[3]
for p in root.rglob('*'):
    if p.is_file():
        try: s=p.read_text(errors='ignore')
        except Exception: continue
        ns=s.replace(st1,'__ST1_PWL__').replace(st2,'__ST2_PWL__')
        if ns != s: p.write_text(ns)
PY
echo "Imported template into: $RAW"
grep -RniE 'pwl|__ST1_PWL__|__ST2_PWL__|ade_e' "$RAW" | head -80 || true
